# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-30 02:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('time', models.DateTimeField()),
                ('location', models.TextField(null=True)),
                ('all_markets', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_edit', 'Can Edit Events'),),
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('timezone', models.CharField(choices=[(b'America/New_York', b'America/New_York'), (b'America/Chicago', b'America/Chicago'), (b'America/Denver', b'America/Denver'), (b'America/Los_Angeles', b'America/Los_Angeles')], default=b'America/New_York', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.CharField(choices=[(b'Yes', b'Yes'), (b'Maybe', b'Maybe'), (b'No', b'No')], default=b'Yes', max_length=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Market'),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvps',
            field=models.ManyToManyField(related_name='rsvps', through='events.RSVP', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.Thread'),
        ),
    ]
