from setuptools import setup

setup(
    name="mdc3",
    version="0.0.1",
    description="An Internet Message Board",
    author="Rev. Johnny Healey",
    author_email="rev.null@gmail.com",
    # TODO can use find_packages?
    packages=[
        'mdc3',
        'mdc3.board',
        'mdc3.events',
        'mdc3.gallery',
        'mdc3.invites',
        'mdc3.moderation',
        'mdc3.pms',
        'mdc3.profiles',
        'mdc3.search',
        'mdc3.shenanigans',
        'mdc3.tags',
        'mdc3.themes',
        'mdc3.util',
    ],
    include_package_data = True,
    install_requires=[
	'bbking==0.0.1',
        'django==1.4.10',
        'south==0.7.3',
        'python-memcached==1.48',
        'pytz==2014.7',
        'django-haystack==1.2.7',
        'simplejson==2.3.0',
        'pysolr==2.1.0-beta',
        'multiprocessing==2.6.2.1',
        'BeautifulSoup==3.2.0',
        'unittest2==0.5.1',
        'mock==0.7.2',
        'django-oembed==0.1.3',
        'django-debug-toolbar==0.11.0',
      ],
    )
