# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-30 02:44


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('base_re', models.CharField(max_length=500)),
                ('base_replace', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('ignore_case', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
