# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-30 02:44


import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField(default=b'')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='pms.PM')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.PM')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pm',
            name='recipients',
            field=models.ManyToManyField(related_name='recieved_pms', through='pms.Recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pm',
            name='root_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_parent_of', to='pms.PM'),
        ),
        migrations.AddField(
            model_name='pm',
            name='sender',
            field=models.ForeignKey(default=b'(no subject)', on_delete=django.db.models.deletion.CASCADE, related_name='sent_pms', to=settings.AUTH_USER_MODEL),
        ),
    ]
