# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-30 02:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_signup', models.GenericIPAddressField()),
                ('last_profile_update', models.DateTimeField(default=datetime.datetime.now)),
                ('profile_views', models.IntegerField(default=0)),
                ('last_events_view', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('aim_name', models.CharField(blank=True, max_length=50)),
                ('gtalk_name', models.CharField(blank=True, max_length=50)),
                ('email_public', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=150)),
                ('info', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('show_images', models.BooleanField(default=True)),
                ('collapse_size', models.IntegerField(default=10)),
                ('favs_first', models.BooleanField(default=False)),
                ('time_zone', models.CharField(choices=[(b'America/New_York', b'America/New_York'), (b'America/Chicago', b'America/Chicago'), (b'America/Denver', b'America/Denver'), (b'America/Los_Angeles', b'America/Los_Angeles')], default=b'America/New_York', max_length=20)),
                ('invite_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invites.Invite')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Market')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
