# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-30 02:44


import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('explanation', models.CharField(blank=True, max_length=2500)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=25)),
                ('used', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_invite', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_approve', 'Can approve invites'),),
            },
        ),
    ]
