# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-07-30 02:44


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('background', models.CharField(default=b'eeeeee', max_length=6)),
                ('row1', models.CharField(default=b'dae1e8', max_length=6)),
                ('row2', models.CharField(default=b'c9d0d8', max_length=6)),
                ('form_background', models.CharField(default=b'ffffff', max_length=6)),
                ('my_posts', models.CharField(default=b'e8e1da', max_length=6)),
                ('font_face', models.CharField(default=b'sans-serif', max_length=64)),
                ('font_size', models.IntegerField(default=95)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
